server:
  port: 9003
spring:
  application:
    name: gateway-service-zuul
  zipkin:
    base-url: http://localhost:9006
  sleuth:
    sampler:
      percentage: 1.0 #日志上传百分比 1.0代表百分百

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
zuul:
  ignoredServices: '*'
  routes:
    initservice: /testinit/**
    queryservice: /testquery/**
  

      
logging:
  path: log/