server:
  port: 9002

spring:
  application:
    name: cloud-config-server
  cloud: 
    config: 
      server: 
        git: 
          uri: https://github.com/Caojunjielove/cloud-config-repo.git
          search-paths: spring-cloud-config

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/

logging:
  path: log/
